version: 2

models:
  - name: mart_finance__monthly_revenue
    description: |
      # Consolidated Financial Performance Dashboard
      **Purpose**: Provides a monthly, multi-dimensional view of sales performance for financial planning and analysis.
      **Primary Users**: Finance Team, Executive Management.
      **Granularity**: Aggregated by Month, Store, Category, and Brand.
      **Sources**: int_localbike__orders_enriched, stg_localbike__stores, stg_localbike__categories, stg_localbike__brands
    columns:
      - name: revenue_month
        description: "The month of the revenue activity (truncated to the first day)."
      - name: store_name
        description: "Name of the store where the sales occurred."
      - name: store_state
        description: "State where the store is located."
      - name: category_name
        description: "Product category (e.g., Mountain Bikes, Road Bikes)."
      - name: brand_name
        description: "Brand of the product sold."
      - name: total_orders
        description: "Total number of orders in this segment for the month."
      - name: total_units_sold
        description: "Total quantity of products sold in this segment for the month."
      - name: gross_revenue
        description: "Total sales value before any discounts are applied (sum of list_price * quantity)."
      - name: total_discounts
        description: "Total monetary value of all discounts given."
      - name: net_revenue
        description: "Final sales value after discounts (Gross Revenue - Total Discounts). This is the key revenue KPI."
      - name: estimated_profit
        description: "Estimated profit based on a 60% margin applied to Net Revenue."
      - name: avg_order_value
        description: "Average value (Net Revenue) of an order within this segment."

  - name: mart_operations__staff_performance
    description: |
      # Staff Ranking and Performance Tracking
      **Purpose**: Ranks sales staff performance within stores and over time to drive operational excellence.
      **Primary Users**: Store Managers, Operations Team.
      **Granularity**: Aggregated by Staff Member and Month.
      **Sources**: int_localbike__staff_enriched
    columns:
      - name: staff_name
        description: "Full name of the sales staff member."
      - name: store_name
        description: "Name of the store where the staff member works."
      - name: manager_name
        description: "Full name of the staff member's manager."
      - name: sales_month
        description: "The month of the performance metrics."
      - name: orders_processed
        description: "Count of distinct orders processed by this staff member in the month."
      - name: unique_customers_served
        description: "Count of unique customers served by this staff member in the month."
      - name: total_items_sold
        description: "Total quantity of items sold by this staff member in the month."
      - name: total_revenue_generated
        description: "Total net revenue generated by the staff member in the month."
      - name: delivery_success_rate
        description: "Percentage of orders successfully delivered for orders processed by this staff."
      - name: avg_shipping_time_days
        description: "Average shipping time in days for orders processed by this staff."
      - name: revenue_rank_monthly
        description: "The staff member's performance rank (1=highest) among all staff for that specific month."
      - name: revenue_rank_store
        description: "The staff member's performance rank within their specific store across all months in the dataset."
      - name: prev_month_revenue
        description: "Total revenue generated by this staff member in the previous month."
      - name: monthly_growth_percent
        description: "Percentage change in revenue generated compared to the previous month for this staff member."

  - name: mart_marketing__customer_360
    description: |
      # Customer Single View for Targeted Marketing
      **Purpose**: Provides a complete profile of each customer with automated marketing recommendations.
      **Primary Users**: Marketing Team, Customer Relationship Management.
      **Granularity**: One row per customer.
      **Sources**: int_localbike__customer_behavior
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
      - name: first_name
        description: "Customer's first name."
      - name: last_name
        description: "Customer's last name."
      - name: city
        description: "City where the customer lives."
      - name: state
        description: "State where the customer lives (2-letter code)."
      - name: niveau_fidelite
        description: |
          Customer value segment:
          - `VIP`: Total revenue > 10,000
          - `Premium`: Total revenue between 5,000 and 10,000
          - `Regular`: Total revenue between 1,000 and 5,000
          - `Occasional`: Total revenue < 1,000
      - name: total_revenue
        description: "Lifetime revenue generated by the customer."
      - name: total_orders
        description: "Total number of orders placed by the customer."
      - name: avg_order_value
        description: "Average value of an order for this customer."
      - name: recency_days
        description: "Days since the customer's last purchase. Key for churn prediction."
      - name: most_recent_purchase
        description: "Date of the customer's most recent order."
      - name: marketing_recommendation
        description: |
          Automated campaign recommendation based on customer tier and activity:
          - `High-Value Reactivation Campaign`: For VIP/Premium customers inactive for >90 days
          - `Loyalty Program Invitation`: For high-spending customers (>5000) active within 30 days
          - `Second Purchase Incentive`: To convert one-time buyers active within 60 days
          - `General Newsletter`: For all other customers