version: 2

models:
  - name: int_localbike__orders_enriched
    description: |
      #  Order Enrichment Table
      **Purpose**: Calculates financial metrics at the order item level.
      This table is the single source of truth for all revenue, discount, and margin calculations.
      **Feeds into**: `mart_finance__monthly_revenue`
      **Logic**: For each order item, calculates:
      - Revenue before discount (list_price * quantity)
      - Revenue after discount (list_price * quantity * (1 - discount))
      - Total discount amount (list_price * quantity * discount)
      **Sources**: stg_localbike__order_items, stg_localbike__orders, stg_localbike__products
    columns:
      - name: order_id
        description: "Unique identifier for the order."
      - name: item_id
        description: "Identifier for the line item within the order."
      - name: product_id
        description: "Identifier of the purchased product."
      - name: quantity
        description: "Quantity of the product ordered."
      - name: list_price
        description: "Price per unit at the time of order."
      - name: discount
        description: "Discount rate applied (between 0 and 1)."
      - name: revenue_before_discount
        description: "Revenue generated by this order line BEFORE discount (list_price * quantity)."
      - name: revenue_after_discount
        description: "Net revenue generated by this order line AFTER discount (list_price * quantity * (1 - discount))."
      - name: total_discount_amount
        description: "Total discount amount applied to this line (list_price * quantity * discount)."
      - name: order_date
        description: "Date when the order was placed."
      - name: customer_id
        description: "ID of the customer who placed the order."
      - name: store_id
        description: "ID of the store where the order was placed."
      - name: staff_id
        description: "ID of the staff member who processed the order."
      - name: product_name
        description: "Name of the purchased product."
      - name: category_id
        description: "ID of the product category."
      - name: brand_id
        description: "ID of the product brand."
      - name: model_year
        description: "Model year of the product."

  - name: int_localbike__customer_behavior
    description: |
      #  Customer Profiling and Segmentation
      **Purpose**: Calculates behavioral metrics (RFM) and segments the customer base.
      Used for targeted marketing and customer lifetime value analysis.
      **Feeds into**: `mart_marketing__customer_360`
      **Logic**: Aggregates customer orders and calculates:
      - Recency: Days since last purchase
      - Frequency: Total number of orders
      - Monetary: Total revenue generated
      - Customer tier: Segmentation based on total revenue
      **Sources**: stg_localbike__orders, stg_localbike__order_items, stg_localbike__customers
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
      - name: first_name
        description: "Customer's first name."
      - name: last_name
        description: "Customer's last name."
      - name: city
        description: "City where the customer lives."
      - name: state
        description: "State where the customer lives (2-letter code)."
      - name: total_orders
        description: "Total number of orders placed by the customer."
      - name: total_items_purchased
        description: "Total quantity of items purchased by the customer."
      - name: total_revenue
        description: "Total revenue generated by this customer (revenue after discount)."
      - name: first_order_date
        description: "Date of the customer's first order."
      - name: last_order_date
        description: "Date of the customer's most recent order."
      - name: avg_order_value
        description: "Average value of an order for this customer (total_revenue / total_orders)."
      - name: recency_days
        description: "Number of days since the customer's last purchase. A low number indicates an active customer."
      - name: frequency
        description: "RFM frequency component (same as total_orders)."
      - name: monetary
        description: "RFM monetary component (same as total_revenue)."
      - name: niveau_fidelite
        description: |
          Customer segment based on their total revenue:
          - `VIP`: Total revenue > 10,000
          - `Premium`: Total revenue between 5,000 and 10,000
          - `Regular`: Total revenue between 1,000 and 5,000
          - `Occasional`: Total revenue < 1,000

  - name: int_localbike__staff_enriched
    description: |
      #  Sales Staff Performance
      **Purpose**: Aggregates key performance indicators (KPIs) for sales staff by month.
      Used to track performance, identify top performers, and inform training needs.
      **Feeds into**: `mart_operations__staff_performance`
      **Logic**: Groups by staff member and month, calculates:
      - Orders processed
      - Unique customers served
      - Total items sold
      - Total revenue generated
      - Delivery success rate
      - Average shipping time
      **Sources**: stg_localbike__staffs, stg_localbike__stores, stg_localbike__orders, stg_localbike__order_items
    columns:
      - name: staff_id
        description: "Unique identifier for the staff member."
      - name: staff_name
        description: "Full name of the staff member (first_name + last_name)."
      - name: store_name
        description: "Name of the store where the staff member works."
      - name: manager_id
        description: "ID of the staff member's manager."
      - name: manager_name
        description: "Full name of the manager."
      - name: sales_month
        description: "The month for which the metrics are aggregated (truncated to the first day of the month)."
      - name: orders_processed
        description: "Count of distinct orders processed by this staff member in the month."
      - name: unique_customers_served
        description: "Count of unique customers served by this staff member in the month."
      - name: total_items_sold
        description: "Total quantity of items sold by this staff member in the month."
      - name: total_revenue_generated
        description: "Total net revenue generated from orders processed by this staff member in the month."
      - name: delivery_success_rate
        description: "Percentage of orders with status = 4 (delivered) for orders processed by this staff."
      - name: avg_shipping_time_days
        description: "Average number of days between order date and shipped date for orders processed by this staff."